server:
  port: 9527

spring:
  application:
    name: sample-vector-redis

logging:
  level:
    root: info
    com.richie.component.vector.redis: debug

platform:
  component:
    vector:
      redis:
        host: ${VECTOR_REDIS_HOST:127.0.0.1}
        port: ${VECTOR_REDIS_PORT:6379}
        db: ${VECTOR_REDIS_DB:0}
        namespace: vectors
        dimension: 768
        metric: COSINE


