spring:
    application:
        name: sample-messaging-pulsar
    profiles:
        include: cache,messaging-pulsar
    main:
        allow-bean-definition-overriding: true
        allow-circular-references: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
server:
    servlet:
        context-path: /messaging
    port: 8889
    jetty:
        threads:
            # 最大线程数 (如果启用了虚拟线程，则不起作用。)
            max: 200
            # 最小线程数 (如果启用了虚拟线程，则不起作用。)
            min: 8
            # 线程队列的最大容量
            max-queue-capacity: 1024
            # 受体线程数（同undertow的IO线程数，用于监听网络端口，并转交selectors中的channel
            # 进行后续处理。默认：-1，根据操作系统和硬件配置动态设置。数量越大并发能力越强，但当
            # CPU处理能力不足是会产生线程资源竞争的情况）
            acceptors: 2
            # Selectors多路复用器数量（默认：-1，根据操作系统和硬件配置动态设置。selector中可
            # 以包含多个channel，类似undertow的worker线程，数量越大并发能力越强，但当CPU处理
            # 能力不足是会产生线程资源竞争的情况）
            selectors: 2
            # 最大线程空闲时间（单位：毫秒）
            idle-timeout: 60000
    undertow:
        threads:
            # IO核心线程数（这些线程主要负责网络事件的监听和分发，以及非阻塞任务。它们的数量通常设置为与系统中的CPU核心数相同或者略少。）
            #          io: 4
            # 工作线程数（通常为io * 8~16[默认8],不是越大越好，要确定服务器是IO密集型还是计算密集型）
            # 这些线程池中的线程用来处理耗时的操作，如业务逻辑处理等。它们的数量可以设置得比 io-threads 多很多，
            # 因为每个 io-thread 可以将工作委派给多个 worker-threads 来并行处理。
            worker: 160
            io: 16

    tomcat:
        threads:
            # 最大线程数（CPU的核心数 * 4）
            max: 64
            # 最小空闲线程数
            min-spare: 32
            # 请求队列的最大容量
            max-queue-capacity: 1024


platform:
    # 组件配置
    component:
        i18n:
            default-locale: en_US
        web:
            cors:
                allow-credentials: true
                allowed-headers: "*"
                allowed-methods: "*"
                allowed-origin: "*"
                exposed-headers: "*"
                enable: true
otel:
    sdk:
        disabled: true
