spring:
    application:
        name: sample-http-httpclient5
    profiles:
        include: http
    main:
        allow-bean-definition-overriding: true
        allow-circular-references: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
        format:
            date-time: yyyy-MM-dd HH:mm:ss

server:
    port: 8890
    undertow:
        threads:
            worker: 200

management:
    endpoints:
        web:
            exposure:
                include: "health,info,metrics,prometheus,redis-stream,redis-stream-links"
    endpoint:
        health:
            show-details: always
            access: unrestricted
        metrics:
            access: unrestricted
        prometheus:
            access: unrestricted
    prometheus:
        metrics:
            export:
                enabled: true
