/*
 * Copyright (c) 2026 Richie (https://www.richie696.cn)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.richie.sample.parser.fixture;

import com.richie.component.parser.DocumentReader;
import org.apache.fesod.sheet.FesodSheet;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.poi.xslf.usermodel.XMLSlideShow;
import org.apache.poi.xslf.usermodel.XSLFSlide;
import org.apache.poi.xslf.usermodel.XSLFTextBox;
import org.apache.poi.xslf.usermodel.XSLFTextShape;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;

import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

/**
 * 启动时生成 6 种格式的测试文件到 {@code target/sample-docs/}。
 * 避免外部资源依赖, sample 启动即可用。
 */
public final class SampleDocumentFixtures {

    private static final Path FIXTURES_DIR = Paths.get("target", "sample-docs");

    private SampleDocumentFixtures() {
    }

    /**
     * 生成所有 sample 测试文件。启动时调用一次。
     *
     * @param reader injected DocumentReader (保留以备后续验证 fixture 解析成功)
     */
    public static void generateAll(DocumentReader reader) throws IOException {
        Files.createDirectories(FIXTURES_DIR);
        System.out.println("[fixtures] generating sample docs in " + FIXTURES_DIR.toAbsolutePath());

        writeText("sample.txt", "This is a plain text file.\n\n" +
                "Used to test atlas-richie-component-document-parser.\n" +
                "Line 1\nLine 2\nLine 3");

        writeText("sample.md", "# Markdown Sample\n\n" +
                "**Bold** and *italic* text.\n\n" +
                "## Section\n\n" +
                "- List item 1\n- List item 2\n- List item 3\n\n" +
                "```java\n" +
                "System.out.println(\"code block\");\n" +
                "```");

        writePdf("sample.pdf");
        writeDocx("sample.docx");
        writeXlsx("sample.xlsx");
        writePptx("sample.pptx");

        System.out.println("[fixtures] generated 6 sample files");
    }

    private static void writeText(String name, String content) throws IOException {
        Path file = FIXTURES_DIR.resolve(name);
        Files.writeString(file, content);
        System.out.println("[fixtures]   wrote " + name + " (" + content.length() + " chars)");
    }

    private static void writePdf(String name) throws IOException {
        Path file = FIXTURES_DIR.resolve(name);
        try (PDDocument doc = new PDDocument()) {
            PDPage page = new PDPage(PDRectangle.A4);
            doc.addPage(page);
            try (PDPageContentStream cs = new PDPageContentStream(doc, page)) {
                cs.beginText();
                cs.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 14);
                cs.newLineAtOffset(50, 700);
                cs.showText("Sample PDF Document");
                cs.newLineAtOffset(0, -20);
                cs.showText("Generated by sample-document-parser");
                cs.newLineAtOffset(0, -20);
                cs.showText("Used to test atlas-richie-component-document-parser.");
                cs.endText();
            }
            doc.save(file.toFile());
        }
        System.out.println("[fixtures]   wrote " + name);
    }

    private static void writeDocx(String name) throws IOException {
        Path file = FIXTURES_DIR.resolve(name);
        try (XWPFDocument doc = new XWPFDocument();
             FileOutputStream out = new FileOutputStream(file.toFile())) {
            XWPFParagraph p1 = doc.createParagraph();
            XWPFRun r1 = p1.createRun();
            r1.setText("Sample Word Document");
            r1.setBold(true);
            r1.setFontSize(18);

            XWPFParagraph p2 = doc.createParagraph();
            XWPFRun r2 = p2.createRun();
            r2.setText("Generated by sample-document-parser. Used to test atlas-richie-component-document-parser.");

            XWPFParagraph p3 = doc.createParagraph();
            XWPFRun r3 = p3.createRun();
            r3.setText("This DOCX file contains multiple paragraphs to verify the streaming parser.");

            doc.write(out);
        }
        System.out.println("[fixtures]   wrote " + name);
    }

    private static void writeXlsx(String name) throws IOException {
        Path file = FIXTURES_DIR.resolve(name);
        List<List<String>> data = List.of(
                List.of("Name", "Department", "Salary"),
                List.of("Alice", "Engineering", "150000"),
                List.of("Bob", "Sales", "120000"),
                List.of("Charlie", "Marketing", "130000")
        );
        try (org.apache.fesod.sheet.ExcelWriter writer =
                     FesodSheet.write(file.toFile()).build()) {
            org.apache.fesod.sheet.write.metadata.WriteSheet sheet =
                    FesodSheet.writerSheet("Employees").build();
            writer.write(data, sheet);
        }
        System.out.println("[fixtures]   wrote " + name);
    }

    private static void writePptx(String name) throws IOException {
        Path file = FIXTURES_DIR.resolve(name);
        try (XMLSlideShow pptx = new XMLSlideShow();
             FileOutputStream out = new FileOutputStream(file.toFile())) {
            XSLFSlide slide = pptx.createSlide();
            XSLFTextBox title = slide.createTextBox();
            title.setAnchor(new java.awt.Rectangle(50, 50, 600, 80));
            XSLFTextShape titleShape = title;
            org.apache.poi.xslf.usermodel.XSLFTextParagraph titlePara = titleShape.getTextParagraphs().get(0);
            org.apache.poi.xslf.usermodel.XSLFTextRun titleRun = titlePara.getTextRuns().get(0);
            titleRun.setText("Sample PowerPoint Slide");
            titleRun.setFontSize(28.0);

            XSLFTextBox body = slide.createTextBox();
            body.setAnchor(new java.awt.Rectangle(50, 150, 600, 200));
            XSLFTextShape bodyShape = body;
            org.apache.poi.xslf.usermodel.XSLFTextParagraph bodyPara = bodyShape.getTextParagraphs().get(0);
            org.apache.poi.xslf.usermodel.XSLFTextRun bodyRun = bodyPara.getTextRuns().get(0);
            bodyRun.setText("Generated by sample-document-parser. Used to test atlas-richie-component-document-parser.");

            pptx.write(out);
        }
        System.out.println("[fixtures]   wrote " + name);
    }
}
