server:
  port: 9525

spring:
  application:
    name: sample-vector-postgresql

logging:
  level:
    root: info
    com.richie.component.vector.postgresql: debug

platform:
  component:
    vector:
      postgresql:
        url: ${VECTOR_PG_URL:jdbc:postgresql://127.0.0.1:5432/vectordb}
        username: ${VECTOR_PG_USERNAME:postgres}
        password: ${VECTOR_PG_PASSWORD:}
        table: vectors
        dimension: 768
        metric: COSINE


