server:
  port: 9526

spring:
  application:
    name: sample-vector-qdrant

logging:
  level:
    root: info
    com.richie.component.vector.qdrant: debug

platform:
  component:
    vector:
      qdrant:
        host: ${QDRANT_HOST:127.0.0.1}
        port: ${QDRANT_PORT:6333}
        collection: vectors
        dimension: 768
        metric: COSINE


