spring:
    main:
        allow-bean-definition-overriding: true
    # Cloud 配置
    cloud:
        function:
            definition: normalProcess
        # Kafka 配置
        stream:
            # 默认binder器（此处支持kafka、RabbitMQ、RocketMQ，但是配置文件内容有少许差异，请参考各队列各自的配置文件）
            default-binder: servicebus
            # 幂等去重服务使用的数据源类型
            datasource: memory
            servicebus:
                bindings:
                    demo1-out-0:
                        producer:
                            namespace: richie-demo
                            connection-string: ${SERVICEBUS_CONNECTION_STRING:Endpoint=sb://servicebus-namespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=}
                            custom-endpoint-address: ${SERVICEBUS_ENDPOINT_ADDRESS:sb://servicebus-namespace.servicebus.windows.net/}
                            default-message-time-to-live: 60000
                            # 发送消息的超时时间（以毫秒为单位）
                            send-timeout: 60000
                            # Service Bus的域名
                            domain-name: ${SERVICEBUS_DOMAIN_NAME:servicebus.windows.net}
                            # 目标实体的名称（例如，主题或队列的名称）
                            entity-name: demo1-topic
                            # 实体的类型，可以是 queue 或 topic
                            entity-type: topic
                            # 队列或主题的最大大小（以兆字节为单位，默认值：1024）
                            max-size-in-megabytes: 1024
                            # 是否使用同步消息发送（true：同步，false：异步）
                            sync: false
                        consumer:
                            namespace: richie-demo
                            receive-mode: peek_lock



            # binding 相关配置
            bindings:
                # OUTPUT：主题1输出通道
                demo1-out-0:
                    destination: demo1-topic
                    content-type: application/json
                    group: menu_queue
                    # 生产者参数配置
                    producer:
                        # 指定该生产者是否自动启动（默认：true）
                        auto-startup: true

                        # 生产者配置请参考 org.springframework.cloud.stream.binder.ProducerProperties

                # OUTPUT：主题2输出通道
                demo2-out-0:
                    destination: demo2-topic
                    content-type: application/json
                    group: menu_queue
                    # 生产者参数配置
                    producer:
                        # 指定该生产者是否自动启动（默认：true）
                        auto-startup: true
                        # 生产者配置请参考 org.springframework.cloud.stream.binder.ProducerProperties

                # INPUT：默认输入通道定义（如需多通道请复制该节点后修改自定义节点）
                # 此处不要修改该INPUT，如果需要在项目中使用多个消费者监听，请
                # 在下方自行添加消费者监听节点，此节点为默认消费者监听器，平台
                # 组件提供了一套默认API
                normalProcess-in-0:
                    destination: demo1-topic,demo2-topic
                    content-type: application/json
                    # 消费者相关配置
                    consumer:
                        # 最大尝试次数
                        max-attempts: 3
                        # 重试起始间隔时间
                        back-off-initial-interval: 500
                        # 重试最大间隔时间
                        back-off-max-interval: 1000
                        # 重试间隔时间乘数
                        back-off-multiplier: 2.0
                        # 更多配置参考 org.springframework.cloud.stream.binder.ConsumerProperties
management:
    health:
        rabbit:
            enabled: false
