server:
  port: 9522

spring:
  application:
    name: sample-vector-milvus

logging:
  level:
    root: info
    com.richie.component.vector.milvus: debug

platform:
  component:
    vector:
      milvus:
        host: ${MILVUS_HOST:127.0.0.1}
        port: ${MILVUS_PORT:19530}
        database: ${MILVUS_DATABASE:default}
        collection: vectors
        dimension: 768
        metric: COSINE


